### ISSUE TITLE
Error TypeError: iterate_repos_to_archive() missing 1 required positional argument: 'operation'

### ISSUE THREAD

**Issue by bybor** [Justintime50/github-archive#36]
Hello,

Here is the command I try, Python 3.9, Windows

    github-archive.exe -s bybor -t XXXXX -l c:\git-archive --clone

Here is the output

```
# GitHub Archive started...

# Making API call to GitHub for starred repos...

# Cloning missing starred repos...

Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\github-archive.exe\__main__.py", line 7, in <module>
  File "C:\Python39\lib\site-packages\github_archive\cli.py", line 134, in main
    GithubArchiveCli().run()
  File "C:\Python39\lib\site-packages\github_archive\cli.py", line 130, in run
    github_archive.run()
  File "C:\Python39\lib\site-packages\github_archive\archive.py", line 140, in run
    self.iterate_repos_to_archive(starred_repos, CLONE_OPERATION)
TypeError: iterate_repos_to_archive() missing 1 required positional argument: 'operation'
```

Could you help with what's going wrong?

Thanks!

**Comment by Justintime50** [comment]
Oof, that's a definite bug I overlooked. Thanks for reporting this! I'll patch this and include it in `v4.1.0` which I'll release in the next couple days.

**Comment by Justintime50** [comment]
Keep an eye on when https://github.com/Justintime50/github-archive/pull/37 gets merged as that'll be when I release the new version. Going to wait a day or two because Coveralls is being weird right now and I want a clean build at release time.

**Comment by bybor** [comment]
Great, thanks! 4.1.0 worked fine. I used it with another new feature you added : `--https` switch.
