### ISSUE TITLE
Unable to download user repos?

### ISSUE THREAD

**Issue by 8465231** [Justintime50/github-archive#55]
So I was testing out your script again and while it seems to work for orgs, anytime I try to download a user account it gives the following error

```Traceback (most recent call last):
  File "/usr/local/bin/github-archive", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/github_archive/cli.py", line 191, in main
    GithubArchiveCli().run()
  File "/usr/local/lib/python3.11/site-packages/github_archive/cli.py", line 187, in run
    github_archive.run()
  File "/usr/local/lib/python3.11/site-packages/github_archive/archive.py", line 126, in run
    self.users.remove(self.authenticated_username)
ValueError: list.remove(x): x not in list```

Is it possible to download user repos with this script?

**Comment by Justintime50** [comment]
Amazing things happen when you properly call your functions correctly instead of like properties (see https://github.com/Justintime50/github-archive/commit/f5706d4b693f72d1576a8557982115a03e7562dd)... This has been patched in `v5.0.3`, make sure to upgrade the package and try again. 

Thanks for reporting this and providing the details I needed to recreate it!

**Comment by 8465231** [comment]
Great, just tested it and at least on the dry run it seems to be working! 

Thanks for the fast fix!

One small tip might be to include the version in the --help.
