### ISSUE TITLE
Getting 502 error

### ISSUE THREAD

**Issue by AlexK89** [Justintime50/github-archive#7]
After doing all set up and ran `python3 github_archive.py` am getting this error: 

Sorry, I'm very far from Python, so might be a dumb question.

Traceback (most recent call last):
  File "github_archive.py", line 272, in <module>
    Archive.run()
  File "github_archive.py", line 219, in run
    for repo in git_org:
  File "/Library/Python/3.7/site-packages/github/PaginatedList.py", line 59, in __iter__
    newElements = self._grow()
  File "/Library/Python/3.7/site-packages/github/PaginatedList.py", line 71, in _grow
    newElements = self._fetchNextPage()
  File "/Library/Python/3.7/site-packages/github/PaginatedList.py", line 201, in _fetchNextPage
    "GET", self.__nextUrl, parameters=self.__nextParams, headers=self.__headers
  File "/Library/Python/3.7/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/Library/Python/3.7/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 502 {"message": "Server Error"}

**Comment by AlexK89** [comment]
I used wrong user TOKEN :)
